name: study
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.2.0
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0
  build_runner: ^2.1.7
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  firebase_auth: ^3.3.6
  firebase_storage: ^10.2.6
  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+5
  provider: ^6.0.2
  uuid: ^3.0.5
  reactive_forms: ^11.0.1
  flutter_speed_dial: ^5.0.0+1
  custom_sliding_segmented_control: ^1.4.0
  material_segmented_control: ^3.1.2
  animated_switch: ^0.0.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^0.14.5
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/picturies/


